---
- name: Setup and Install Packages on Azure VM
  hosts: webservers
  become: yes
  become_user: azureuser  # Replace with your Azure VM username

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Upgrade all packages (again)
      apt:
        upgrade: dist

  vars:
    packages:
      - docker-ce
      - nodejs=12
      - npm
      - python3
      - nginx
      - tree
      - vim
      - git
      - pm2
